### ISSUE TITLE
Exclude wrong travel durations

### ISSUE THREAD

**Issue by JonasBchrt** [juliuste/api.direkt.bahn.guru#2]
Occasionally, the pop-ups on https://direkt.bahn.guru/ show travel durations that are by 360 h = 15 d too high. These numbers are reproducible.

Examples:

- [London St. Pancras - Paris Nord](https://direkt.bahn.guru/?origin=7001424)
- [Lille Europe - Dunkerque](https://direkt.bahn.guru/?origin=8704949)
- [Lille Europe - London St. Pancras](https://direkt.bahn.guru/?origin=8704949)

The wrong travel durations seem to come from the API. Without having tracked down the specific cause for this issue, a simple fix might be to filter out these travel times in the [`reachableForDay` function](https://github.com/juliuste/direkt.bahn.guru-rest/blob/9c771951311c5ce52ceb48830fbc5d39984ac249/lib/reachableFrom.js#L19). [Currently, there seems to be no train on the world that runs for more than 206 h.](https://en.wikipedia.org/wiki/Longest_train_services#Top_50_train_services,_by_distance)

![image](https://user-images.githubusercontent.com/57848364/116105646-69d23600-a6a9-11eb-98c7-658782cd9fc4.png)
![image](https://user-images.githubusercontent.com/57848364/116107007-87ec6600-a6aa-11eb-8f3b-a00d53e09607.png)

**Comment by juliuste** [comment]
Hey Jonas, thanks for reporting this! I implemented the change you suggested in 0852c571ca330ae8c767a628efea315a8ba41071, which should fix the examples you posted above.

Unfortunately, the endpoint we're using seems to have several bugs which lead to this weird behaviour. I'm pretty sure there are also cases of trains running for 100h or so within Germany, which won't be fixed with this static upper bound. Since the API endpoint that we're using is deprecated, there is little hope that these will get fixed soon. To fully resolve this, one would need to completely change the way this service is working. (It would probably make sense to calculate all durations from a validated, static dataset instead of using the deprecated API on-demand, but since such a dataset is not public as of now, one would need to write a scraper first, which takes additional time).

I'll close this issue for the time being, but if you - or anyone else reading this - finds examples of trains that are still broken (ones that take less than 210h, I'm pretty sure that these exist and that I saw them already in the past), please re-open and post screenshots/descriptions here.
